### ISSUE TITLE
enrol_coursepilot Plugin scaffold and settings

### ISSUE THREAD

**Issue by dvdcastro** [sofhouse/moodle-enrol_coursepilot#1]
### Story

As a user I can install and configure `enrol_coursepilot` as an enrollment plugin that doesn't allow manual enrollments

### AC

1. Exists new plugin called `enrol_coursepilot`
2. The plugin is identified as an enrollment plugin but does not allow enrolling students yet
3. Exists new settings for the plugin:
	1. Template categories:
		1. Type: Multiple course category selector
		2. Default: Empty
		3. Help text: These categories will be used when listing template courses for copying.
	2. Formations categories:
		1. Type: Multiple course category selector
		2. Default: Empty
		3. Help text: These categories will be used for validating when users are enrolled to formations courses.
4. Catalyst build should be added.
```yaml
name: ci

on: [push, pull_request]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    # secrets:
    #   # Required if you plan to publish (uncomment the below)
    #   moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      disable_release : true
```
The `version.php` file should read `$plugin->supported = [405, 405];`
